### ISSUE TITLE
[REFACTOR] Scrap End-to-end 리팩토링

### ISSUE THREAD

**Issue by ye0ngeun** [FISOLUTION/iluvit-backend#367]
## 📌 Feature Issue

- Scrap Controller, Service, Repository 관련 코드를 아래 TO-DO에 따라 리팩토링 한다

## 📝 To-do

- [ ]  메서드 네이밍 규칙을 따라 repository 메서드 변경
- [ ]  ResponseEntity로 변경
- [ ]  DTO 컨벤션에 맞게 이름 및 필드 이름 변경
- [ ]  노션 API 명세서 업데이트
- [ ]  API 테스트 완료
