### ISSUE TITLE
✨Black User 관련 로직 추가

### ISSUE THREAD

**Issue by dltjdn** [FISOLUTION/iluvit-backend#376]
## 📌 Description
- BlackUser를 추가하면서 관련된 api에 정책상 필요한 로직들을 추가한다

## 📝 To-do
- [ ] 로그인 api : 에러 로직 추가
- [ ] 자동로그인 ( 유저 조회 ) api : 에러 로직 추가
- [ ] 회원가입 api : 에러 로직 추가
- [ ] 탈퇴 api : 블랙 유저에 정보 저장하는 로직 추가
