### ISSUE TITLE
♻️ local profile 삭제

### ISSUE THREAD

**Issue by dltjdn** [FISOLUTION/iluvit-backend#457]
## 📌 Description
- application-local 프로필을 삭제하고 logs경로만 secret 파일들만 ec2경로로 넣어줍니다

## 📝 To-do
- [x] local profile 삭제, dev,prod 프로필 로컬 logs 경로 ./logs로 수정 ( secret 파일들은 그대로 우분투 경로 유지 )
- [x] application.yml 수정
- [x] logback-spring.xml 수정
